# Generated by Django 2.1.5 on 2019-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='perfil',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
