# Generated by Django 2.1.5 on 2019-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20190711_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeeditem',
            name='status_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='perfil',
            field=models.TextField(max_length=255),
        ),
    ]
