# Generated by Django 2.1.5 on 2019-07-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_auto_20190711_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='perfil',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
