# Generated by Django 2.1.5 on 2019-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20190711_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
