# Generated by Django 2.1.5 on 2019-07-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_userprofile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_StarUser',
            field=models.BooleanField(default=True),
        ),
    ]
